#inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/ClassLength:
  Exclude:
    - "myapp.rb"

Style/Documentation:
  Exclude:
    - "myapp.rb"

Metrics/BlockLength:
  Exclude:
    - "myapp.rb"
    - "db/schema.rb"

Metrics/BlockNesting:
  Exclude:
    - "myapp.rb"

Layout/LineLength:
  Exclude:
    - "myapp.rb"

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
